spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:15.3:///springit
  kafka:
    bootstrap-servers: ${kafka.bootstrapServers}
    consumer:
      group-id: spring-it-itest
  mail:
    host: localhost
    port: ${greenmail.port}
    username: ${greenmail.user}
    password: ${greenmail.password}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

payment:
  url: http://localhost:${wiremock.stripePort}

gcs:
  bucket: itest-pictures
