spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:15.3:///springit
  kafka:
    bootstrap-servers: ${kafka.bootstrapServers}
    consumer:
      group-id: spring-it-itest

payment:
  url: http://localhost:${wiremock.stripePort}
